"""
Django settings for auth_api project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import dj_database_url
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-r+ht&xe9n_2+p#5cnss5f1bc_orj$*o86h1gw^57$$o3cb4zvl'
    
# SECRET_KEY = '2&(=ib3a$(j^9chz=l+aw+d*q+u-i14f05*4o67k_t7z*5i9sp'

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY','2&(=ib3a$(j^9chz=l+aw+d*q+u-i14f05*4o67k_t7z*5i9sp')



# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False
DEBUG = os.environ.get('DJANGO_DEBUG', '') != 'False'

ALLOWED_HOST = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'auth_sys.apps.AuthSysConfig',

    'rest_framework',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'auth_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'auth_api.wsgi.application'

SESSION_COOKIE_SECURE = True

SECURE_SSL_REDIRECT = True 

SECURE_HSTS_SECONDS = 3600

SECURE_HSTS_INCLUDE_SUBDOMAINS = True

SECURE_HSTS_PRELOAD = True 

CSRF_TRUSTED_ORIGINS = ['https://authenticationapidrf-production.up.railway.app/']

CSRF_COOKIE_SECURE = True

CSRF_COOKIE_DOMAIN = 'https://authenticationapidrf-production.up.railway.app'


# REST FRAMEWORK DEFAULT CLASSES

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES':[
        'rest_framework.authentication.TokenAuthentication',
    ]
}

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    # 'default': {
    #     'database_url':'postgresql://postgres:b8NLuNn4noaq2Ck6Fv1E@containers-us-west-63.railway.app:7865/railway',
    #     'ENGINE': 'django.db.backends.postgresql_psycopg2',
    #     'NAME': 'auth_system_db',
    #     'USER': 'postgres',
    #     'HOST': 'localhost',
    #     'PASSWORD': '2030',
    #     'PORT': '5432'
    # }

    'default': {
        'database_url':'postgresql://postgres:b8NLuNn4noaq2Ck6Fv1E@containers-us-west-63.railway.app:7865/railway',
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'railway',
        'USER': 'postgres',
        'HOST': 'containers-us-west-63.railway.app',
        'PASSWORD': 'b8NLuNn4noaq2Ck6Fv1E',
        'PORT': '7865'
    }
}

# UPDATE DATABASE CONFIGURATION 

db_from_env = dj_database_url.config(conn_max_age=500)
DATABASES['default'].update(db_from_env)


#AUTH USER MODEL 

AUTH_USER_MODEL = 'auth_sys.Users'


# AUTHENTICATION BACKENDS 

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'auth_sys.backends.PasswordlessAuth',
)


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
